version: '3'

networks:
  pib-network:
    driver: bridge

services:
  flask-app:
    image: flask_api
    build:
      context: .
      dockerfile: ./pib_api/flask/Dockerfile
    networks:
      - pib-network
    ports:
      - "5000:5000"
    volumes:
      - ./pib_api/flask/:/app
      - programs:/root/cerebra_programs
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/pibdata.db
      - PIB_BLOCKLY_SERVER_URL=http://pib-blockly-server:2442
    command: "bash -c 'flask --app run db upgrade && flask --app run seed_db && flask --app run run --host 0.0.0.0'"
    depends_on:
      - pib-blockly-server

  pib-blockly-server:
    image: pib-blockly-server
    build:
      context: ./pib_blockly/pib_blockly_server
      dockerfile: ./Dockerfile
    networks:
      - pib-network
    ports: 
      - "2442:2442"
    command: "node /app/dist/pib_blockly_server_bundle.js"

  ros-camera:
    image: ros-camera
    privileged: true
    build:
      context: ./ros_packages
      dockerfile: ./camera/Dockerfile
    profiles:
      - camera
    command: ros2 run oak_d_lite stereo
    # Volume binding should not be necessary here,
    # but removing will stop the camera from showing pictures for some reason
    volumes:
      - /dev/:/dev/
    devices:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - pib-network

  ros-motors:
    image: ros_motors
    build:
      context: .
      dockerfile: ./ros_packages/motors/Dockerfile
    profiles:
      - motors
    command: ros2 launch motors launch.py
    environment:
      - FLASK_API_BASE_URL=http://flask-app:5000
      - PIB_BLOCKLY_SERVER_URL=http://pib-blockly-server:2442
      - TINKERFORGE_HOST=tinkerforge-brickd
      - TINKERFORGE_PORT=4223
    networks:
      - pib-network
    restart: always
    depends_on:
      - tinkerforge-brickd
      - flask-app

  ros-voice-assistant:
    image: ros_voice_assistant
    privileged: true
    build:
      context: .
      dockerfile: ./ros_packages/voice_assistant/Dockerfile
    profiles:
      - voice_assistant
    command: ros2 launch voice_assistant launch.py
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - ALSA_CARD=Generic
      - FLASK_API_BASE_URL=http://flask-app:5000
      - VOICE_ASSISTANT_DIR=/app/ros2_ws/voice_assistant
    env_file:
      - password.env
    volumes:
      - /media/dyan/project/projects/voice/:/data/voice
      - /dev/snd:/dev/snd
      - /dev/dsp:/dev/dsp
      - /etc/machine-id:/etc/machine-id
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    networks:
      - pib-network
    restart: always
    depends_on:
      - flask-app
      - pib-blockly-server

  ros-programs:
    image: ros_programs
    build:
      context: .
      dockerfile: ./ros_packages/programs/Dockerfile
    command: ros2 launch programs launch.py
    environment:
      - FLASK_API_BASE_URL=http://flask-app:5000
      - PIB_BLOCKLY_SERVER_URL=http://pib-blockly-server:2442
      - TINKERFORGE_HOST=tinkerforge-brickd
      - TINKERFORGE_PORT=4223
      - PYTHON_BINARY=/usr/bin/python3
      - PROGRAM_DIR=/ros2_ws/cerebra_programs
      - VOICE_ASSISTANT_DIR=/app/ros2_ws/voice_assistant
    volumes:
      - programs:/ros2_ws/cerebra_programs
    restart: always
    networks:
      - pib-network
    depends_on:
      - pib-blockly-server
      - flask-app

  ros-display:
    image: ros-display
    privileged: true
    build:
      context: .
      dockerfile: ./ros_packages/display/Dockerfile
    profiles:
      - display
    volumes:
      # this is a socket that is used by the x-windowing-system
      # for cmmunication betweem clients and servers on the same
      # machine. By mounting the socket of the docker-host, the 
      # display-node uses the x-server running on the host for
      # graphics-related communication
      - /tmp/.X11-unix:/tmp/.X11-unix 
    environment:
      - STATIC_IMAGE_DIR=/app/ros2_ws/display/static_images
      - DISPLAY=:0.0
    command: ros2 launch display launch.py
    restart: always
    networks:
      - pib-network

  rosbridge-ws:
    build:
      context: ./ros_packages
      dockerfile: ./rosbridge/Dockerfile
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml
    networks:
      - pib-network

  tinkerforge-brickd:
    privileged: true
    image: tinkerforge-brickd
    profiles:
      - motors
    networks:
      - pib-network
    build:
      context: .
      dockerfile: Dockerfile.brickd
    ports:
      - "4223:4223"
    tty: true
    # Mount bricklets
    devices:
      - /dev/gpiomem:/dev/gpiomem
    depends_on:
      - flask-app


volumes:
  programs:
