version: '3'

networks:
  pib-network:
    driver: bridge

services:  
  flask-app:
    image: flask_api
    build:
      context: .
      dockerfile: ./pib_api/flask/Dockerfile
    networks:
      - pib-network
    ports:
      - "5000:5000"
    volumes:
      - ./pib_api/flask/:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/pibdata.db
      - PIBLY_SERVER_URL=http://pibly-server:2442
    command: "bash -c 'flask --app run db upgrade && flask --app run seed_db && flask --app run run --host 0.0.0.0 --debug'"
    depends_on:
      - pibly-server

  pibly-server:
    image: pibly-server
    build:
      context: ./pibly/pibly_server/
      dockerfile: ./Dockerfile
    networks:
      - pib-network
    ports: 
      - "2442:2442"
    command: "node /app/dist/pibly_server_bundle.js"

  ros-packages:
    image: ros_packages
    privileged: true
    build:
      context: .
      dockerfile: ./ros_packages/Dockerfile
    networks:
      - pib-network
    # For Linux, mount sound and camera
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "9090:9090"
    environment:
      - FLASK_API_BASE_URL=http://flask-app:5000
      - PIBLY_SERVER_URL=http://pibly-server:2442
      - TINKERFORGE_HOST=tinkerforge-brickd
      - TINKERFORGE_PORT=4223
      - PYTHON_BINARY=/usr/local/bin/python3
      - PROGRAM_DIR=/ros_ws/cerebra_programs
      - VOICE_ASSISTANT_DIR=/ros_ws/voice_assistant
      - PUBLIC_API_CONFIG_FILE_PATH=/home/pib/public_api/config.json
    env_file:
      - password.env
    command: "/bin/bash -c 'source docker_run_all_nodes.sh'"
    depends_on:
      - flask-app
      - pibly-server

  tinkerforge-brickd:
    privileged: true
    image: tinkerforge-brickd
    networks:
      - pib-network
    build:
      context: .
      dockerfile: Dockerfile.brickd
    ports:
      - "4223:4223"
    tty: true
    # Mount bricklets
    devices:
      - /dev/gpiomem:/dev/gpiomem