Match User pib-power
    PasswordAuthentication yes
    KbdInteractiveAuthentication no
    PermitEmptyPasswords yes
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
    ForceCommand /usr/local/sbin/pib-power-ssh-command
